config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get('/', {to: 'ideas#index', as: :root})
  
  
  resources :ideas do
    resources :reviews, only: [:create, :destroy]
    resources :likes, shallow: true, only: [:create, :destroy]

    get :liked, on: :collection
  end
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
    include CanCan::Ability
  
    def initialize(user)
      # Define abilities for the passed in user here. For example:
      #
        user ||= User.new # guest user (not logged in)
      #
      # The first argument to `can` is the action you are giving the user
      # permission to do.
      # If you pass :manage it will apply to every action. Other common actions
      # here are :read, :create, :update and :destroy.
      #
      # The second argument is the resource the user can perform the action on.
      # If you pass :all it will apply to every resource. Otherwise pass a Ruby
      # class of the resource.
      #
      # The third argument is an optional hash of conditions to further filter the
      # objects.
      # For example, here the user can only update published articles.
      #
      #   can :update, Article, :published => true
      #
      # See the wiki for details:
      # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  
      alias_action :create, :read, :update, :destroy, to: :crud
  
      can(:crud, Idea) do |idea|
        idea.user == user
      end
  
      can :crud, Review do |review|
        review.user == user 
      end

    can :destroy, Like do |like|
      like.user == user
    end

    can :like, Idea do |idea|
      user.persisted? && user != idea.user
    end

    end
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
    validates(:title, presence: true, uniqueness: true)
    validates(:body, presence: true, length: {minimum: 50})
    has_many :likes, dependent: :destroy
    has_many :reviews, dependent: :destroy
    has_many :likers, through: :likes, source: :user
    belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :idea

  validates :idea_id, uniqueness: {
    scope: :user_id,
    message: "has already been liked"
  }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :idea
  belongs_to :user
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :ideas, dependent: :nullify
    has_many :reviews, dependent: :nullify
    has_many :likes, dependent: :destroy
    has_many :liked_questions, through: :likes, source: :idea


    validates :email, presence: true, uniqueness: true,
              format:  /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    private
    def current_user
        if session[:user_id].present?
            @current_user || User.find_by(id: session[:user_id])
        end
        
    end
    helper_method(:current_user)

    def user_signed_in?
        current_user.present?
    end
    helper_method :user_signed_in?

    def authenticate_user!
        unless user_signed_in?
            flash[:danger] = "You must sign in or sign up first!"
            redirect_to new_session_path
        end
    end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
        before_action :authenticate_user!, except: [:index, :show]
        before_action :find_idea, only: [:show, :edit, :update, :destroy]
        before_action :authorize!, only: [:edit, :update, :destroy]
    
        def new
            @idea=Idea.new
        end
    
        def index
            @ideas=Idea.all

        end
    
        def edit 
        end
    
        def update
            idea_params = params.require(:idea).permit(:title, :body)
            if @idea.update idea_params
                redirect_to idea_path(@idea)
            else
                render :edit
            end 
        end
    
        def create
            @idea=Idea.new idea_params
            @idea.user = current_user
    
            if @idea.save
                flash[:notice] = "idea created successfully"
    
                redirect_to idea_path(@idea)
            else
                render :new
            end            
        end
    
        def show
            @review = Review.new
            @reviews = @idea.reviews.order(created_at: :desc)
            @like = @idea.likes.find_by(user: current_user)

        end
    
        def destroy
            @idea.destroy
            redirect_to ideas_path
          end


        def liked
            @ideas = current_user.liked_ideas.order('likes.created_at DESC')
        end

    
        private 
    
        def idea_params
            params.require(:idea).permit(:title, :body)
        end
    
        def find_idea
            @idea = Idea.find(params[:id])
        end
    
        def authorize!
            redirect_to root_path, alert: 'Not Authorized' unless can?(:crud, @idea)
        end
    end
    

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user!
    before_action :find_idea, only: [ :create ]
    before_action :authorize_user!, only: [ :create ]
  
    def create
      like = Like.new(idea: @idea, user: current_user)
      if like.save
        flash[:success] = "Idea liked"
      else
        flash[:danger] = like.errors.full_messages.join(", ")
      end
      redirect_to root_path
    end
  
    def destroy
      like = current_user.likes.find params[:id]
      if can? :destroy, like
        like.destroy
        flash[:success] = "Idea unliked"
      else
        flash[:alert] = "Can't delete like"
      end
      redirect_to root_path
    end
  

    private
  
    def find_idea
      @idea = Idea.find(params[:idea_id])
    end
  
    def authorize_user!
      unless can? :like, @idea
        flash[:danger] = "We know you like your own idea!"
        redirect_to idea_path(@idea)
      end
    end
  end
  

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :authorize!, only: [:destroy]

    def create
        @idea = Idea.find(params[:idea_id])
        @review = Review.new review_params
        @review.idea = @idea
        @review.user = current_user

        if @review.save
            redirect_to idea_path(@idea)
        else
            @reviews = @idea.reviews.order(created_at: :desc)
            render 'ideas/show'
    end
end

    def destroy
        @review = Review.find params[:id]
        @review.destroy
        redirect_to idea_path(@review.idea)
    end

    
private

    def review_params
        params.require(:review).permit(:body, :rating)
    end

    def authorize!
        redirect_to root_path, alert: 'Not Authorized' unless can?(:crud, @review)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
  
    def create
      user = User.find_by_email params[:email]
      if user&.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to root_path, notice: "Logged In"
      else
        flash[:alert] = "Wrong email or password"
        render :new
      end
    end
  
    def destroy
      session[:user_id] = nil
      redirect_to root_path, notice: "Logged out!"
    end
  
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController


    def new
        @user = User.new
    end

    def create
        @user = User.new user_params

        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: "Logged in!"
        else
            render :new
        end
    end


        private

        def user_params
            params.require(:user).permit(
              :name,
              :email,
              :password,
              :password_confirmation
            )
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideas/_form.html.erb
<% if @idea.errors.any? %>
  <ul>
    <% @idea.errors.full_messages.each do |msg|%>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%# https://guides.rubyonrails.org/form_helpers.html %>
<%= form_for @idea do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_field :body %>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/ideas/edit.html.erb
<h1>Edit Idea</h1>

<%= render "form" %>

app/views/ideas/index.html.erb
<div class="card-container">
<% @ideas.each do |idea|  %>
    <hr>
    <h4><%= link_to idea.title, idea_path(idea) %></h4>
    <p><%= idea.body %></p>

    <div class= "likes">
    <p>By <%= idea.user.name  || 'DELETED'%>  <% like = idea.likes.find_by(user: current_user) %>
    <% if like.present? && can?(:destroy, like) %>
    <button type="button" class="btn-outline-dark">
      <%= link_to "Liked", like_path(like), method: :delete %>
      </button>
    <% elsif can?(:like, idea)%>
    <button type="button" class="btn-outline-dark">
      <%= link_to "Like", idea_likes_path(idea) , method: :post %>
      </button></p>
  <% end %>
  <small>
    <%= pluralize(idea.likes.count, "like") %>
  </small>
  </div>
<% end %>
</div>
<hr>

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render "form" %>

app/views/ideas/show.html.erb
<h1><%= @idea.title %></h1>
<p><%= @idea.body %></p>

<p><%= time_ago_in_words(@idea.created_at)%> ago</p>
<h4>By <%= @idea.user.name  || 'DELETED'%></h4>
<% if can? :crud, @idea %>
<%= link_to "Edit", edit_idea_path(@idea), class: "btn-med"%>
<%= link_to "Delete", idea_path(@idea), class: "btn-med", method: :delete, data: {confirm: "Are you sure?"} %>
<% end %>

<div>
<button type="button" class="btn-outline-dark">
  <% if @like.present? && can?(:destroy, @like) %>
    <%= link_to "Liked", like_path(@like), method: :delete %>
  <% elsif can?(:like, @idea)%>
    <%= link_to "Like", idea_likes_path(@idea), method: :post %>
  <% end %>
  </button>
  <small>
    <%= pluralize(@idea.likes.count, "like") %>
  </small>
</div>

<%= form_with(model: [@idea, @review], local: true) do |f| %>
<% if @review.errors.any? %>
<br>
  <ul>
    <% @review.errors.full_messages.each do |msg|%>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<br>
<div class="form-group">
  <%= f.text_area(
  :body,
  cols: 50,
  rows: 5,
  placeholder: "What are your thoughts?",
  class: "form-control"
  ) %>
</div>
<%= f.submit class: "btn-outline-dark" %>
<% end %>

<hr />

<ul class="list-group">
  <% @reviews.each do |review| %>
    <li>
      <p class="list-group-item">
        <%= review.body %> <br />
         Reviewed <%= time_ago_in_words(review.created_at) %> ago
        </small>
        <% if can? :crud, review %>
        <small>
        <%= link_to(
          "Delete",
          idea_review_path(@idea, review),
          method: :delete,
          data: {
            confirm: "Are you sure?"
          }
        ) %>
      </small>
      
      <% end %>
      </p>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Idea Factory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
  <nav>
  <div class="branding">
  <%= link_to image_tag('idea.png', size: "60"), root_path %> <br>
  <%= link_to "Idea Factory", root_path %>
  </div>
  

  <div class="menu">
  <%#= flash[:notice] || flash[:alert] %>
      <% if user_signed_in?%>
        Hello <%= current_user.name %>     &emsp;
        <%= link_to "Sign Out", session_path, method: :delete,
        data: {confirm: "Are you sure you want to log out?"}%>
      <%else%>
        <%= link_to "Login", new_session_path %> &emsp;
        <%= link_to "Sign Up", new_user_path %>
      <% end %>
    <br> <br>
    <button type="button" class="btn-outline-dark">
    <%= link_to 'New Idea', new_idea_path %>
    </button>
    <% flash.each do |type, message| %>
      <div class="flash flash-<%= type %>">
        <%= message %>
      </div>
    <% end %>
    </div>

  </nav>

    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_with model: @user, local: true do |f| %>

    <% if @user.errors.any?%>
        <p>
            <%= @user.errors.full_messages.join(', ')%>
        </p>
    <% end %>


    <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
    </div>


    <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
    </div>

    <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
    </div>

    <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    </div>

    <%= f.submit class: "btn-outline-dark"  %>
    <% end %>